// Location data for dynamic country and state/province selection

export interface LocationData {
  [countryCode: string]: {
    name: string;
    states?: {
      [stateCode: string]: string;
    };
  };
}

export const locationData: LocationData = {
  US: {
    name: 'United States',
    states: {
      AL: 'Alabama',
      AK: 'Alaska',
      AZ: 'Arizona',
      AR: 'Arkansas',
      CA: 'California',
      CO: 'Colorado',
      CT: 'Connecticut',
      DE: 'Delaware',
      FL: 'Florida',
      GA: 'Georgia',
      HI: 'Hawaii',
      ID: 'Idaho',
      IL: 'Illinois',
      IN: 'Indiana',
      IA: 'Iowa',
      KS: 'Kansas',
      KY: 'Kentucky',
      LA: 'Louisiana',
      ME: 'Maine',
      MD: 'Maryland',
      MA: 'Massachusetts',
      MI: 'Michigan',
      MN: 'Minnesota',
      MS: 'Mississippi',
      MO: 'Missouri',
      MT: 'Montana',
      NE: 'Nebraska',
      NV: 'Nevada',
      NH: 'New Hampshire',
      NJ: 'New Jersey',
      NM: 'New Mexico',
      NY: 'New York',
      NC: 'North Carolina',
      ND: 'North Dakota',
      OH: 'Ohio',
      OK: 'Oklahoma',
      OR: 'Oregon',
      PA: 'Pennsylvania',
      RI: 'Rhode Island',
      SC: 'South Carolina',
      SD: 'South Dakota',
      TN: 'Tennessee',
      TX: 'Texas',
      UT: 'Utah',
      VT: 'Vermont',
      VA: 'Virginia',
      WA: 'Washington',
      WV: 'West Virginia',
      WI: 'Wisconsin',
      WY: 'Wyoming'
    }
  },
  CA: {
    name: 'Canada',
    states: {
      AB: 'Alberta',
      BC: 'British Columbia',
      MB: 'Manitoba',
      NB: 'New Brunswick',
      NL: 'Newfoundland and Labrador',
      NS: 'Nova Scotia',
      ON: 'Ontario',
      PE: 'Prince Edward Island',
      QC: 'Quebec',
      SK: 'Saskatchewan',
      NT: 'Northwest Territories',
      NU: 'Nunavut',
      YT: 'Yukon'
    }
  },
  GB: {
    name: 'United Kingdom',
    states: {
      ENG: 'England',
      SCT: 'Scotland',
      WLS: 'Wales',
      NIR: 'Northern Ireland'
    }
  },
  AU: {
    name: 'Australia',
    states: {
      NSW: 'New South Wales',
      VIC: 'Victoria',
      QLD: 'Queensland',
      WA: 'Western Australia',
      SA: 'South Australia',
      TAS: 'Tasmania',
      ACT: 'Australian Capital Territory',
      NT: 'Northern Territory'
    }
  },
  DE: {
    name: 'Germany',
    states: {
      BW: 'Baden-Württemberg',
      BY: 'Bavaria',
      BE: 'Berlin',
      BB: 'Brandenburg',
      HB: 'Bremen',
      HH: 'Hamburg',
      HE: 'Hesse',
      MV: 'Mecklenburg-Vorpommern',
      NI: 'Lower Saxony',
      NW: 'North Rhine-Westphalia',
      RP: 'Rhineland-Palatinate',
      SL: 'Saarland',
      SN: 'Saxony',
      ST: 'Saxony-Anhalt',
      SH: 'Schleswig-Holstein',
      TH: 'Thuringia'
    }
  },
  FR: {
    name: 'France',
    states: {
      ARA: 'Auvergne-Rhône-Alpes',
      BFC: 'Bourgogne-Franche-Comté',
      BRE: 'Brittany',
      CVL: 'Centre-Val de Loire',
      COR: 'Corsica',
      GES: 'Grand Est',
      HDF: 'Hauts-de-France',
      IDF: 'Île-de-France',
      NOR: 'Normandy',
      NAQ: 'Nouvelle-Aquitaine',
      OCC: 'Occitanie',
      PDL: 'Pays de la Loire',
      PAC: 'Provence-Alpes-Côte d\'Azur'
    }
  },
  JP: {
    name: 'Japan',
    states: {
      HOKKAIDO: 'Hokkaido',
      TOHOKU: 'Tohoku',
      KANTO: 'Kanto',
      CHUBU: 'Chubu',
      KANSAI: 'Kansai',
      CHUGOKU: 'Chugoku',
      SHIKOKU: 'Shikoku',
      KYUSHU: 'Kyushu',
      OKINAWA: 'Okinawa'
    }
  },
  IN: {
    name: 'India',
    states: {
      AP: 'Andhra Pradesh',
      AR: 'Arunachal Pradesh',
      AS: 'Assam',
      BR: 'Bihar',
      CT: 'Chhattisgarh',
      GA: 'Goa',
      GJ: 'Gujarat',
      HR: 'Haryana',
      HP: 'Himachal Pradesh',
      JH: 'Jharkhand',
      KA: 'Karnataka',
      KL: 'Kerala',
      MP: 'Madhya Pradesh',
      MH: 'Maharashtra',
      MN: 'Manipur',
      ML: 'Meghalaya',
      MZ: 'Mizoram',
      NL: 'Nagaland',
      OR: 'Odisha',
      PB: 'Punjab',
      RJ: 'Rajasthan',
      SK: 'Sikkim',
      TN: 'Tamil Nadu',
      TG: 'Telangana',
      TR: 'Tripura',
      UP: 'Uttar Pradesh',
      UT: 'Uttarakhand',
      WB: 'West Bengal'
    }
  },
  BR: {
    name: 'Brazil',
    states: {
      AC: 'Acre',
      AL: 'Alagoas',
      AP: 'Amapá',
      AM: 'Amazonas',
      BA: 'Bahia',
      CE: 'Ceará',
      DF: 'Distrito Federal',
      ES: 'Espírito Santo',
      GO: 'Goiás',
      MA: 'Maranhão',
      MT: 'Mato Grosso',
      MS: 'Mato Grosso do Sul',
      MG: 'Minas Gerais',
      PA: 'Pará',
      PB: 'Paraíba',
      PR: 'Paraná',
      PE: 'Pernambuco',
      PI: 'Piauí',
      RJ: 'Rio de Janeiro',
      RN: 'Rio Grande do Norte',
      RS: 'Rio Grande do Sul',
      RO: 'Rondônia',
      RR: 'Roraima',
      SC: 'Santa Catarina',
      SP: 'São Paulo',
      SE: 'Sergipe',
      TO: 'Tocantins'
    }
  },
  MX: {
    name: 'Mexico',
    states: {
      AGU: 'Aguascalientes',
      BCN: 'Baja California',
      BCS: 'Baja California Sur',
      CAM: 'Campeche',
      CHP: 'Chiapas',
      CHH: 'Chihuahua',
      COA: 'Coahuila',
      COL: 'Colima',
      DIF: 'Mexico City',
      DUR: 'Durango',
      GUA: 'Guanajuato',
      GRO: 'Guerrero',
      HID: 'Hidalgo',
      JAL: 'Jalisco',
      MEX: 'Estado de México',
      MIC: 'Michoacán',
      MOR: 'Morelos',
      NAY: 'Nayarit',
      NLE: 'Nuevo León',
      OAX: 'Oaxaca',
      PUE: 'Puebla',
      QUE: 'Querétaro',
      ROO: 'Quintana Roo',
      SLP: 'San Luis Potosí',
      SIN: 'Sinaloa',
      SON: 'Sonora',
      TAB: 'Tabasco',
      TAM: 'Tamaulipas',
      TLA: 'Tlaxcala',
      VER: 'Veracruz',
      YUC: 'Yucatán',
      ZAC: 'Zacatecas'
    }
  },
  // Countries without states/provinces (will just show country dropdown)
  AD: { name: 'Andorra' },
  AE: { name: 'United Arab Emirates' },
  AF: { name: 'Afghanistan' },
  AG: { name: 'Antigua and Barbuda' },
  AI: { name: 'Anguilla' },
  AL: { name: 'Albania' },
  AM: { name: 'Armenia' },
  AO: { name: 'Angola' },
  AQ: { name: 'Antarctica' },
  AR: { name: 'Argentina' },
  AS: { name: 'American Samoa' },
  AT: { name: 'Austria' },
  AW: { name: 'Aruba' },
  AX: { name: 'Åland Islands' },
  AZ: { name: 'Azerbaijan' },
  BA: { name: 'Bosnia and Herzegovina' },
  BB: { name: 'Barbados' },
  BD: { name: 'Bangladesh' },
  BE: { name: 'Belgium' },
  BF: { name: 'Burkina Faso' },
  BG: { name: 'Bulgaria' },
  BH: { name: 'Bahrain' },
  BI: { name: 'Burundi' },
  BJ: { name: 'Benin' },
  BL: { name: 'Saint Barthélemy' },
  BM: { name: 'Bermuda' },
  BN: { name: 'Brunei' },
  BO: { name: 'Bolivia' },
  BQ: { name: 'Caribbean Netherlands' },
  BS: { name: 'Bahamas' },
  BT: { name: 'Bhutan' },
  BV: { name: 'Bouvet Island' },
  BW: { name: 'Botswana' },
  BY: { name: 'Belarus' },
  BZ: { name: 'Belize' },
  CC: { name: 'Cocos (Keeling) Islands' },
  CD: { name: 'Democratic Republic of the Congo' },
  CF: { name: 'Central African Republic' },
  CG: { name: 'Republic of the Congo' },
  CH: { name: 'Switzerland' },
  CI: { name: 'Côte d\'Ivoire' },
  CK: { name: 'Cook Islands' },
  CL: { name: 'Chile' },
  CM: { name: 'Cameroon' },
  CN: { name: 'China' },
  CO: { name: 'Colombia' },
  CR: { name: 'Costa Rica' },
  CU: { name: 'Cuba' },
  CV: { name: 'Cape Verde' },
  CW: { name: 'Curaçao' },
  CX: { name: 'Christmas Island' },
  CY: { name: 'Cyprus' },
  CZ: { name: 'Czech Republic' },
  DJ: { name: 'Djibouti' },
  DK: { name: 'Denmark' },
  DM: { name: 'Dominica' },
  DO: { name: 'Dominican Republic' },
  DZ: { name: 'Algeria' },
  EC: { name: 'Ecuador' },
  EE: { name: 'Estonia' },
  EG: { name: 'Egypt' },
  EH: { name: 'Western Sahara' },
  ER: { name: 'Eritrea' },
  ES: { name: 'Spain' },
  ET: { name: 'Ethiopia' },
  FI: { name: 'Finland' },
  FJ: { name: 'Fiji' },
  FK: { name: 'Falkland Islands' },
  FM: { name: 'Micronesia' },
  FO: { name: 'Faroe Islands' },
  GA: { name: 'Gabon' },
  GD: { name: 'Grenada' },
  GE: { name: 'Georgia' },
  GF: { name: 'French Guiana' },
  GG: { name: 'Guernsey' },
  GH: { name: 'Ghana' },
  GI: { name: 'Gibraltar' },
  GL: { name: 'Greenland' },
  GM: { name: 'Gambia' },
  GN: { name: 'Guinea' },
  GP: { name: 'Guadeloupe' },
  GQ: { name: 'Equatorial Guinea' },
  GR: { name: 'Greece' },
  GS: { name: 'South Georgia and the South Sandwich Islands' },
  GT: { name: 'Guatemala' },
  GU: { name: 'Guam' },
  GW: { name: 'Guinea-Bissau' },
  GY: { name: 'Guyana' },
  HK: { name: 'Hong Kong' },
  HM: { name: 'Heard Island and McDonald Islands' },
  HN: { name: 'Honduras' },
  HR: { name: 'Croatia' },
  HT: { name: 'Haiti' },
  HU: { name: 'Hungary' },
  ID: { name: 'Indonesia' },
  IE: { name: 'Ireland' },
  IL: { name: 'Israel' },
  IM: { name: 'Isle of Man' },
  IO: { name: 'British Indian Ocean Territory' },
  IQ: { name: 'Iraq' },
  IR: { name: 'Iran' },
  IS: { name: 'Iceland' },
  IT: { name: 'Italy' },
  JE: { name: 'Jersey' },
  JM: { name: 'Jamaica' },
  JO: { name: 'Jordan' },
  KE: { name: 'Kenya' },
  KG: { name: 'Kyrgyzstan' },
  KH: { name: 'Cambodia' },
  KI: { name: 'Kiribati' },
  KM: { name: 'Comoros' },
  KN: { name: 'Saint Kitts and Nevis' },
  KP: { name: 'North Korea' },
  KR: { name: 'South Korea' },
  KW: { name: 'Kuwait' },
  KY: { name: 'Cayman Islands' },
  KZ: { name: 'Kazakhstan' },
  LA: { name: 'Laos' },
  LB: { name: 'Lebanon' },
  LC: { name: 'Saint Lucia' },
  LI: { name: 'Liechtenstein' },
  LK: { name: 'Sri Lanka' },
  LR: { name: 'Liberia' },
  LS: { name: 'Lesotho' },
  LT: { name: 'Lithuania' },
  LU: { name: 'Luxembourg' },
  LV: { name: 'Latvia' },
  LY: { name: 'Libya' },
  MA: { name: 'Morocco' },
  MC: { name: 'Monaco' },
  MD: { name: 'Moldova' },
  ME: { name: 'Montenegro' },
  MF: { name: 'Saint Martin' },
  MG: { name: 'Madagascar' },
  MH: { name: 'Marshall Islands' },
  MK: { name: 'North Macedonia' },
  ML: { name: 'Mali' },
  MM: { name: 'Myanmar' },
  MN: { name: 'Mongolia' },
  MO: { name: 'Macao' },
  MP: { name: 'Northern Mariana Islands' },
  MQ: { name: 'Martinique' },
  MR: { name: 'Mauritania' },
  MS: { name: 'Montserrat' },
  MT: { name: 'Malta' },
  MU: { name: 'Mauritius' },
  MV: { name: 'Maldives' },
  MW: { name: 'Malawi' },
  MY: { name: 'Malaysia' },
  MZ: { name: 'Mozambique' },
  NA: { name: 'Namibia' },
  NC: { name: 'New Caledonia' },
  NE: { name: 'Niger' },
  NF: { name: 'Norfolk Island' },
  NG: { name: 'Nigeria' },
  NI: { name: 'Nicaragua' },
  NL: { name: 'Netherlands' },
  NO: { name: 'Norway' },
  NP: { name: 'Nepal' },
  NR: { name: 'Nauru' },
  NU: { name: 'Niue' },
  NZ: { name: 'New Zealand' },
  OM: { name: 'Oman' },
  PA: { name: 'Panama' },
  PE: { name: 'Peru' },
  PF: { name: 'French Polynesia' },
  PG: { name: 'Papua New Guinea' },
  PH: { name: 'Philippines' },
  PK: { name: 'Pakistan' },
  PL: { name: 'Poland' },
  PM: { name: 'Saint Pierre and Miquelon' },
  PN: { name: 'Pitcairn' },
  PR: { name: 'Puerto Rico' },
  PS: { name: 'Palestine' },
  PT: { name: 'Portugal' },
  PW: { name: 'Palau' },
  PY: { name: 'Paraguay' },
  QA: { name: 'Qatar' },
  RE: { name: 'Réunion' },
  RO: { name: 'Romania' },
  RS: { name: 'Serbia' },
  RU: { name: 'Russia' },
  RW: { name: 'Rwanda' },
  SA: { name: 'Saudi Arabia' },
  SB: { name: 'Solomon Islands' },
  SC: { name: 'Seychelles' },
  SD: { name: 'Sudan' },
  SE: { name: 'Sweden' },
  SG: { name: 'Singapore' },
  SH: { name: 'Saint Helena' },
  SI: { name: 'Slovenia' },
  SJ: { name: 'Svalbard and Jan Mayen' },
  SK: { name: 'Slovakia' },
  SL: { name: 'Sierra Leone' },
  SM: { name: 'San Marino' },
  SN: { name: 'Senegal' },
  SO: { name: 'Somalia' },
  SR: { name: 'Suriname' },
  SS: { name: 'South Sudan' },
  ST: { name: 'São Tomé and Príncipe' },
  SV: { name: 'El Salvador' },
  SX: { name: 'Sint Maarten' },
  SY: { name: 'Syria' },
  SZ: { name: 'Eswatini' },
  TC: { name: 'Turks and Caicos Islands' },
  TD: { name: 'Chad' },
  TF: { name: 'French Southern Territories' },
  TG: { name: 'Togo' },
  TH: { name: 'Thailand' },
  TJ: { name: 'Tajikistan' },
  TK: { name: 'Tokelau' },
  TL: { name: 'Timor-Leste' },
  TM: { name: 'Turkmenistan' },
  TN: { name: 'Tunisia' },
  TO: { name: 'Tonga' },
  TR: { name: 'Turkey' },
  TT: { name: 'Trinidad and Tobago' },
  TV: { name: 'Tuvalu' },
  TW: { name: 'Taiwan' },
  TZ: { name: 'Tanzania' },
  UA: { name: 'Ukraine' },
  UG: { name: 'Uganda' },
  UM: { name: 'United States Minor Outlying Islands' },
  UY: { name: 'Uruguay' },
  UZ: { name: 'Uzbekistan' },
  VA: { name: 'Vatican City' },
  VC: { name: 'Saint Vincent and the Grenadines' },
  VE: { name: 'Venezuela' },
  VG: { name: 'British Virgin Islands' },
  VI: { name: 'United States Virgin Islands' },
  VN: { name: 'Vietnam' },
  VU: { name: 'Vanuatu' },
  WF: { name: 'Wallis and Futuna' },
  WS: { name: 'Samoa' },
  YE: { name: 'Yemen' },
  YT: { name: 'Mayotte' },
  ZA: { name: 'South Africa' },
  ZM: { name: 'Zambia' },
  ZW: { name: 'Zimbabwe' }
};

// Helper functions
export const getCountryOptions = (): Array<{ value: string; label: string }> => {
  return Object.entries(locationData)
    .map(([code, data]) => ({
      value: code,
      label: data.name
    }))
    .sort((a, b) => a.label.localeCompare(b.label));
};

export const getStateOptions = (countryCode: string): Array<{ value: string; label: string }> => {
  const country = locationData[countryCode];
  if (!country || !country.states) {
    return [];
  }
  
  return Object.entries(country.states)
    .map(([code, name]) => ({
      value: code,
      label: name
    }))
    .sort((a, b) => a.label.localeCompare(b.label));
};

export const getCountryName = (countryCode: string): string => {
  return locationData[countryCode]?.name || countryCode;
};

export const getStateName = (countryCode: string, stateCode: string): string => {
  return locationData[countryCode]?.states?.[stateCode] || stateCode;
};
